version: "3"
services:
  frontend:
    build: ./front-end
    stdin_open: true
    ports: 
      - "3000:3000"
    restart: unless-stopped
    networks:
      - fullstack
  
  # backend:
  #   build: ./back-end
  #   stdin_open: true
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - fullstack
  #   restart: unless-stopped
  #   depends_on:
  #     - mongo
  

  backend:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - '5000:5000'
    environment:
      DB_CONNECTION_STRING: 'mongodb+srv://enessertkan:Password123@cluster0.55mfjdg.mongodb.net/?retryWrites=true&w=majority'
    restart: unless-stopped
  #   depends_on:
  #     - mongo

  # mongo:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - fullstack
  #   volumes:
  #     - mongo-data:/data/db

networks: 
  fullstack:
    driver: bridge

volumes:
  mongo-data:
    driver: local
